name: 🛠️ Deploy to GitHub Pages

# Позволяет запускать вручную из Actions → Run workflow
on:
  push:
    branches:
      - main    # или master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'    # ваша версия, например 22

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Токен, автоматически подставляется Actions runner-ом
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # ветка, откуда Pages будут брать файлы
          publish_branch: gh-pages
          # optional: чистить перед пушем
          clean: true